"""add plant taxonomy fields: type, lifecycle, zones, light, size, additional GDD thresholds

Revision ID: 07f95c4dc184
Revises: bb73a9271aad
Create Date: 2025-12-18 14:42:58.826479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f95c4dc184'
down_revision: Union[str, Sequence[str], None] = 'bb73a9271aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add timestamp columns as nullable first, then set defaults for existing rows
    op.add_column('plant_taxonomy', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('plant_taxonomy', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('plant_taxonomy', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE plant_taxonomy SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE plant_taxonomy SET updated_at = NOW() WHERE updated_at IS NULL")
    
    # Now make them NOT NULL
    op.alter_column('plant_taxonomy', 'created_at', nullable=False)
    op.alter_column('plant_taxonomy', 'updated_at', nullable=False)
    op.add_column('plant_taxonomy', sa.Column('plant_type', sa.String(length=64), nullable=True))
    op.add_column('plant_taxonomy', sa.Column('lifecycle', sa.String(length=32), nullable=True))
    op.add_column('plant_taxonomy', sa.Column('foliage_type', sa.String(length=32), nullable=True))
    op.add_column('plant_taxonomy', sa.Column('usda_zone_min', sa.String(length=8), nullable=True))
    op.add_column('plant_taxonomy', sa.Column('usda_zone_max', sa.String(length=8), nullable=True))
    op.add_column('plant_taxonomy', sa.Column('light_requirements', sa.String(length=32), nullable=True))
    op.add_column('plant_taxonomy', sa.Column('mature_height_ft', sa.Float(), nullable=True))
    op.add_column('plant_taxonomy', sa.Column('mature_width_ft', sa.Float(), nullable=True))
    op.add_column('plant_taxonomy', sa.Column('gdd_fertilize_min', sa.Float(), nullable=True))
    op.add_column('plant_taxonomy', sa.Column('gdd_spray_min', sa.Float(), nullable=True))
    op.add_column('plant_taxonomy', sa.Column('gdd_divide_min', sa.Float(), nullable=True))
    op.add_column('plant_taxonomy', sa.Column('gdd_transplant_min', sa.Float(), nullable=True))
    op.add_column('plant_taxonomy', sa.Column('gdd_harvest_min', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant_taxonomy', 'gdd_harvest_min')
    op.drop_column('plant_taxonomy', 'gdd_transplant_min')
    op.drop_column('plant_taxonomy', 'gdd_divide_min')
    op.drop_column('plant_taxonomy', 'gdd_spray_min')
    op.drop_column('plant_taxonomy', 'gdd_fertilize_min')
    op.drop_column('plant_taxonomy', 'mature_width_ft')
    op.drop_column('plant_taxonomy', 'mature_height_ft')
    op.drop_column('plant_taxonomy', 'light_requirements')
    op.drop_column('plant_taxonomy', 'usda_zone_max')
    op.drop_column('plant_taxonomy', 'usda_zone_min')
    op.drop_column('plant_taxonomy', 'foliage_type')
    op.drop_column('plant_taxonomy', 'lifecycle')
    op.drop_column('plant_taxonomy', 'plant_type')
    op.drop_column('plant_taxonomy', 'deleted_at')
    op.drop_column('plant_taxonomy', 'updated_at')
    op.drop_column('plant_taxonomy', 'created_at')
    # ### end Alembic commands ###
