"""Initial migration: create all tables

Revision ID: bb73a9271aad
Revises: 
Create Date: 2025-12-18 12:38:40.483772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb73a9271aad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_taxonomy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('botanical_name', sa.String(length=255), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=True),
    sa.Column('cultivar', sa.String(length=255), nullable=True),
    sa.Column('is_minnesota_native', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('gdd_prune_min', sa.Float(), nullable=True),
    sa.Column('gdd_plant_min', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_taxonomy_botanical_name'), 'plant_taxonomy', ['botanical_name'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('usda_zone', sa.String(length=8), nullable=True),
    sa.Column('soil_profile', sa.Text(), nullable=True),
    sa.Column('sun_exposure_map', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_client_id'), 'properties', ['client_id'], unique=False)
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_table('weather_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(length=64), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('t_min_c', sa.Float(), nullable=True),
    sa.Column('t_max_c', sa.Float(), nullable=True),
    sa.Column('gdd_base_50f', sa.Float(), nullable=True),
    sa.Column('gdd_cumulative_50f', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_readings_reading_date'), 'weather_readings', ['reading_date'], unique=False)
    op.create_index(op.f('ix_weather_readings_station_id'), 'weather_readings', ['station_id'], unique=False)
    op.create_table('living_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('plant_taxon_id', sa.Integer(), nullable=False),
    sa.Column('location_note', sa.String(length=255), nullable=True),
    sa.Column('health_status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plant_taxon_id'], ['plant_taxonomy.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_living_assets_property_id'), 'living_assets', ['property_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('living_asset_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scheduled_for', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('triggered_by_gdd', sa.Boolean(), nullable=False),
    sa.Column('trigger_threshold', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['living_asset_id'], ['living_assets.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_property_id'), 'work_orders', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_property_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_living_assets_property_id'), table_name='living_assets')
    op.drop_table('living_assets')
    op.drop_index(op.f('ix_weather_readings_station_id'), table_name='weather_readings')
    op.drop_index(op.f('ix_weather_readings_reading_date'), table_name='weather_readings')
    op.drop_table('weather_readings')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_client_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_plant_taxonomy_botanical_name'), table_name='plant_taxonomy')
    op.drop_table('plant_taxonomy')
    # ### end Alembic commands ###
